### ISSUE TITLE
Reverie not working with Wordpress 3.6

### ISSUE THREAD

**Issue by oudin** [milohuang/reverie#217]
Hi:

I upgraded to Wordpress 3.6 and I'm now getting the following error 

[18:08:29.113] TypeError: jQuery(...).foundation is not a function @ http://123.123.123.134/sitename/:673

I'm now using Reverie 4.0.0 theme with a child theme

I attempted to update to Reverie 4.3.1 however I was still got the same "not a function" error and the drop down menu stopped working so I reverted back to 4.0.0.

Any help on how I can solve this
